//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugginCreation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Employees
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DateID { get; set; }
    
        public virtual tb_tableGrid tb_tableGrid { get; set; }
    }
}
