//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugginCreation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAutor
    {
        public int ID_Autor { get; set; }
        public string Autor { get; set; }
    }
}
